dist: bionic
branches:
  only:
    - master

addons:
  apt:
    - g++-multilib

matrix:
  include:
    - name: 'Windows version (cross-compiled from Linux)'
      env:
        - CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=../byond-extools/cmake/i686-w64-mingw32.cmake"
    - name: 'Linux version'

script:
  - mkdir build
  - cd build
  - cmake ../byond-extools $CMAKE_ARGS
  - cmake --build .
